version: "3.9"

services:
  app:
    container_name: mvp-api-anuncios
    image: python-3.9-mvp-api-anuncios
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - "5002:5002"